export const BATCH_ROLLBACK = 'BATCH_ROLLBACK';
export const BATCH_TOP_PACKAGES = 'BATCH_TOP_PACKAGES';
export const BATCH_TOP_AGENTS = 'BATCH_TOP_AGENTS';
export const BATCH_EXPIRED_POLICIES = 'BATCH_EXPIRED_POLICIES';
